### ISSUE TITLE
Link printed by server.sh doesn't work

### ISSUE THREAD

**Issue by hannobraun** [the-drunk-coder/ruffbox#3]
When starting server.sh, the following output is printed:
```
Serving HTTP on 0.0.0.0 port 1234 (http://0.0.0.0:1234/) ...
```
When opening that link in a browser, the following error message appears in a popup:
> AudioWorklet isn't supported... It cannot work.

I believe the reason is that `AudioWorklet` is only available in a secure context (see https://developers.google.com/web/updates/2017/12/audio-worklet). The workaround I found is to connect to http://localhost:1234/ instead, as http://localhost is considered secure for local testing (as per the previous link).

**Comment by the-drunk-coder** [comment]
Hi Hanno,

it's true that it only works with https when loaded from a remote server, but it should work in a non-secure environment you start it locally. 

What browser are you using ? Unfortunately AudioWorklet (in its raw form) is only available in Chromium/Chrome and Opera at the moment. There's supposedly some ways to work around that but I haven't hat time to look into that yet ... 

**EDIT:** Sorry, only just now I saw your paragraph about the difference between using `localhost` and `0.0.0.0`. You're right, using the latter in the browser address line doesn't work. 

The link in the server script is just the default output by the python server, I'm not sure if that can be changed.

**Comment by the-drunk-coder** [comment]
Added a note to the readme. Should be sufficient !
