### ISSUE TITLE
Example site error: Cannot perform TypedArray.prototype.set on a detached ArrayBuffer

### ISSUE THREAD

**Issue by SephReed** [the-drunk-coder/ruffbox#4]
The demo wasn't working.  I found this error in the console:

```
Uncaught TypeError: Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer
    at Float32Array.set (<anonymous>)
    at AudioWorkletProcessor.process (worklet.js?t=1600116398531:185)
```

**Comment by the-drunk-coder** [comment]
Hi, I remember this happen in the past sometimes but I haven't encountered this error in years, so I assume some advances in the underlying infrastructure fixed this. If you still encounter this please let me know (also, sorry for not seeing this in 2 years :sweat_smile: )
